apiVersion: v1
kind: Service
metadata:
  name: scale-python-service
spec:
  selector:
    app: scale-python
  ports:
  - protocol: "TCP"
    port: 440
    targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-python
spec:
  selector:
    matchLabels:
      app: scale-python
  replicas: 4
  template:
    metadata:
      labels:
        app: scale-python
    spec:
      containers:
      - name: scale-python
        image: scale
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
